{% set version = '1.2.0' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-loader.java
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/SantanderMetGroup/loadeR.java/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 545e30e6077c9288f692dbbc41090ee7f33be7953dc003a81d2a77b0e52e72e5

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}filesystem        # [win]
    - {{ posix }}git
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rjava
  run:
    - r-base
    - r-rjava

test:
  commands:
    - $R -e "library('loadeR.java')"           # [not win]
    - "\"%R%\" -e \"library('loadeR.java')\""  # [win]

about:
  home: https://github.com/SantanderMetGroup/loadeR.java
  license: GPL-3.0-or-later
  summary: Initializes the Unidata's NetCDF Java Library that implements the full CDM model,
    including all other .jar dependencies.
  license_family: GPL3
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - cofinoa
    - mor427unican
    

# Package: loadeR.java
# Depends: rJava, R(>= 3.1.0)
# Type: Package
# Title: Loader of the NetCDF Java Library in R
# Version: 1.1.1
# Date: 2018-04-26
# Authors@R: as.person(c( "Santander Meteorology Group <http://meteo.unican.es> [cph]", "Joaquin Bedia <bediaj@unican.es> [aut, cre]", "Antonio Cofino <antonio.cofino@unican.es> [aut]", "Max Tuni <max@predictia.es> [ctb]", "Manuel Vega <manuel.vega@unican.es> [ctb]" ))
# Maintainer: Joaquin Bedia <bediaj@unican.es>
# BugReports: https://github.com/SantanderMetGroup/loadeR.java/issues
# Description: Initializes the Unidata's NetCDF Java Library that implements the full CDM model, including all other .jar dependencies.
# License: GPL(>=3) + file LICENSE
# RoxygenNote: 6.0.1
